apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp
  name: web-service
spec:
  ports:
  - nodePort: 31337
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webapp
  sessionAffinity: None
  type: NodePort